- name: Configure Erlang Repos
  ansible.builtin.shell: https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

- name: Configure RabbitMQ Repos
  ansible.builtin.shell: https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

- name: Install RabbitMQ Server
  ansible.builtin.yum:
    name: rabbitmq
    state: installed

- name: Start RabbitMQ Service
  ansible.builtin.systemd:
    name: rabbitmq
    state: restarted
    enabled: true

- name: Add RabbitMQ Application User
  community.rabbitmq.rabbitmq_user:
     user: roboshop
     password: roboshop123
     vhost: /
     configure_priv: .*
     read_priv: .*
     write_priv: .*
     state: present
